POST http://localhost:8080/api/v1/licenses/replace
Content-Type: application/json
Authorization:Bearer 54d1ba805e2a4891aeac9299b618945e

{
  "customerId": "6371863a-cb98-4847-8d77-c9b1cb983ced",
  "type": "device",
  "inn": "231456",
  "title": "customer title",
  "description": "customer descr",
  "Licenses": [
    {
      "licenseId": "code1",
      "productType": "waiter*",
      "callbackUrl": "http://sHnCZMi.biz/YRoACmF*",
      "count": 3,
      "licenseKey": "license key 1",
      "activationAt": "1988-12-01 09:58:10",
      "expirationAt": "1999-07-17 01:14:10",
      "description": "desc1"
    },
    {
      "licenseId": "code2",
      "productType": "courier",
      "callbackUrl": "http://sHnCZMi.biz/callback",
      "count": 1,
      "licenseKey": "",
      "activationAt": "2020-12-01 09:58:09",
      "expirationAt": "2025-07-17 01:14:17",
      "description": "desc2"
    }
  ]
}